management:
  security:
    enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  sleuth:
    sampler:
      percentage: 1.0
